linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - durationcheck
    - exportloopref
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    enable-all-rules: true
    rules:
      - name: argument-limit
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: file-header
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: function-length
        disabled: true
      - name: unexported-naming
        disabled: true
      - name: add-constant
        disabled: true
      - name: unhandled-error
        disabled: true
      - name: deep-exit
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: nested-structs
        disabled: true
      - name: confusing-results
        disabled: true
      - name: empty-lines
        disabled: true
