version: '3'

output: 'group'

tasks:
  lint:
    cmds:
      - golangci-lint run --timeout=5m

  goimports:
    cmds:
      - goimports -w .

  grpc:
    vars:
      OUT_DIR: internal/proto
    cmds:
      - rm -rf internal/proto/*
      - protoc --go_out={{.OUT_DIR}} --go-grpc_out={{.OUT_DIR}} --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative -I ../proto $(find ../proto -iname "*.proto")