@startuml app_services
package appservices <<Frame>> {
    interface ConfigReader{
        + GetAppConfig():AppConfig{}
    }
    class gRPCmessaging{
        + Run()
        + Stop()
    }
    class TelegramBotService{
        + Run()
        + Stop()
        + SendMessage(Name, Message)
        - makeMenu()
    }
    
    package telebot <<Frame>>{
        class Bot 
    }

    package grpc <<Frame>>{
        class Server
    }

    package proto\com\informertelegrambot{
        class UnimplementedInformerBotMessagingServer
    }
    
    gRPCmessaging .> TelegramBotService
    gRPCmessaging ..> Server
    gRPCmessaging ..> UnimplementedInformerBotMessagingServer
    TelegramBotService .> Bot
        
}
@enduml