@startuml app_services
package appservices <<Frame>> {
    interface ConfigReader{
        + GetAppConfig():AppConfig{}
    }
    class gRPCmessaging
    class TelegramBotService{
        + Run()
        + Stop()
        + SendMessage(Name, Message)
        - makeMenu()
    }
    class telebot 
    gRPCmessaging .> TelegramBotService
    TelegramBotService .> telebot
}
@enduml