@startuml domain
package domain <<Frame>> {
    class Message
    class Subscriber
    interface InfChannel{
        SendMessage():error
	    GetChType():InfChType
    }
    interface SubscrRepository{
        + AddSubscriber(Subscriber)
        + UpdateSubscriber(Subscriber)
        + GetSubscriberByName():Subscriber
        + GetSubscribers()
    }
    interface MsgRepository{
        + AddMessage(Message)
        + UpdateMessage(Message)
        + GetMessageByID():Message
        + GetMessagesByStatus()
    }
    SubscrRepository ..> Subscriber
    MsgRepository ..> Message
}
