@startuml links
!include domain.puml
!include domain_services.puml
'remove AdminMgr
'remove Admin 
together {
    SenderService ..> SubscrRepository
    SenderService ..> MsgRepository
    SenderService ..> InfChannel

    MsgReceptionMgr ..> MsgRepository

    AdminMgr ..> SubscrRepository
    AdminMgr ..> MsgRepository
}
@enduml